name = "gleam_community_path"
version = "0.1.0"
licences = ["Apache-2.0"]
description = "Path parsing and manipulation"
repository = { type = "github", user = "gleam-community", repo = "path" }

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
